import { EtherProvider } from "./Context/Ether"
import Footer from "./components/Footer"
import NavBar from "./components/NavBar"
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  <html>
    <body>
      <EtherProvider>
        <NavBar />
          {children}
        <Footer />
      </EtherProvider>
    </body>
  </html>
  )
}
